<!-- Variable to use across site -->
<!--#set var="studentpath" value="/students/ksilprasert/" -->

<!-- Common declaration -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- CSS -->
<link rel="stylesheet" href="<!--#echo var='studentpath' -->comp1950project/css/normalize.css" />
<link rel="stylesheet" href="<!--#echo var='studentpath' -->comp1950project/css/bootstrap.min.css" />
<link rel="stylesheet" href="<!--#echo var='studentpath' -->comp1950project/css/projectstyle.css" />

<!-- Java Script -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="<!--#echo var='studentpath' -->comp1950project/js/jquery.slidereveal.min.js"></script>
<script type="text/javascript" src="<!--#echo var='studentpath' -->comp1950project/js/bootstrap.min.js"></script>

